// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Core.Persistent.Context;
using Microsoft.EntityFrameworkCore;

namespace Sys.Entity.Models;

public partial class SysDbContext : BaseDbContext
{
    public SysDbContext(DbContextOptions<SysDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SysApi> SysApis { get; set; }

    public virtual DbSet<SysMenuPermission> SysMenuPermissions { get; set; }

    public virtual DbSet<SysRole> SysRoles { get; set; }

    public virtual DbSet<SysRolePermission> SysRolePermissions { get; set; }

    public virtual DbSet<SysUser> SysUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<SysApi>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.Property(e => e.CreatedBy).HasComment("创建人");
            entity.Property(e => e.CreatedTime).HasComment("创建时间");
            entity.Property(e => e.ModifyBy).HasComment("修改人");
            entity.Property(e => e.ModifyTime).HasComment("修改时间");
        });

        modelBuilder.Entity<SysMenuPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_menu_permission", tb => tb.HasComment("页面权限"));

            entity.Property(e => e.Id).HasComment("主键");
            entity.Property(e => e.ComponentPath).HasComment("组件路径");
            entity.Property(e => e.CreatedBy).HasComment("创建人");
            entity.Property(e => e.CreatedTime).HasComment("创建时间");
            entity.Property(e => e.ExternalUrl).HasComment("外部链接");
            entity.Property(e => e.Icon).HasComment("图标");
            entity.Property(e => e.Iframe).HasComment("内嵌iframe地址");
            entity.Property(e => e.ModifiedBy).HasComment("修改人");
            entity.Property(e => e.ModifiedTime).HasComment("修改时间");
            entity.Property(e => e.ParentId).HasComment("父级");
            entity.Property(e => e.PermissionCode).HasComment("权限标识");
            entity.Property(e => e.RoutePath).HasComment("前端路由");
            entity.Property(e => e.Seq).HasComment("排序");
            entity.Property(e => e.Title).HasComment("菜单标题");
            entity.Property(e => e.Type)
                .HasDefaultValueSql("'menu'")
                .HasComment("菜单类型");
            entity.Property(e => e.Visible)
                .HasDefaultValueSql("'1'")
                .HasComment("是否显示(1=显示,0=隐藏)");
        });

        modelBuilder.Entity<SysRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_role", tb => tb.HasComment("角色"));

            entity.Property(e => e.Id).HasComment("主键");
            entity.Property(e => e.Code).HasComment("角色代码");
            entity.Property(e => e.Enable)
                .HasDefaultValueSql("'1'")
                .HasComment("启用状态");
            entity.Property(e => e.Name).HasComment("名称");
        });

        modelBuilder.Entity<SysRolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_role_permission", tb => tb.HasComment("角色与权限关联表"));

            entity.Property(e => e.CreatedTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建时间");
            entity.Property(e => e.PermissionId).HasComment("权限ID（对应sys_menu_permission.id 或 sys_api.id）");
            entity.Property(e => e.PermissionType).HasComment("权限类型(menu=页面权限, api=接口权限)");
            entity.Property(e => e.RoleId).HasComment("角色ID");

            entity.HasOne(d => d.Role).WithMany(p => p.SysRolePermissions).HasConstraintName("fk_rolepermission_role");
        });

        modelBuilder.Entity<SysUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_user", tb => tb.HasComment("系统用户表"));

            entity.Property(e => e.Id).HasComment("主键");
            entity.Property(e => e.CreatedBy).HasComment("创建人");
            entity.Property(e => e.CreatedTime).HasComment("创建时间");
            entity.Property(e => e.Email).HasComment("邮箱");
            entity.Property(e => e.LastLoginIp).HasComment("最后登录ip");
            entity.Property(e => e.LastLoginTime).HasComment("最后登录时间");
            entity.Property(e => e.MobileArea).HasComment("区号");
            entity.Property(e => e.MobilePhoneNumber).HasComment("手机号");
            entity.Property(e => e.ModifiedBy).HasComment("修改人");
            entity.Property(e => e.ModifiedTime).HasComment("修改时间");
            entity.Property(e => e.Name).HasComment("姓名");
            entity.Property(e => e.Password).HasComment("密码");
            entity.Property(e => e.Salt).HasComment("加密盐");
            entity.Property(e => e.Status).HasComment("状态");
            entity.Property(e => e.Username).HasComment("用户名");

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "SysUserRole",
                    r => r.HasOne<SysRole>().WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_userrole_role"),
                    l => l.HasOne<SysUser>().WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_userrole_user"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.ToTable("sys_user_role", tb => tb.HasComment("用户与角色关联表"));
                        j.HasIndex(new[] { "RoleId" }, "fk_userrole_role");
                        j.IndexerProperty<int>("UserId")
                            .HasComment("用户ID")
                            .HasColumnName("user_id");
                        j.IndexerProperty<int>("RoleId")
                            .HasComment("角色ID")
                            .HasColumnName("role_id");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}