// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.Persistent.Entities;
using System;
using System.Collections.Generic;

namespace Sys.Entity.Models;

public partial class SysApi : AuditableEntity<Guid>
{

    public string Name { get; set; }

    public string Method { get; set; }

    public string Path { get; set; }

    public string Module { get; set; }

    public string PermissionCode { get; set; }

   
}