// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Core.Persistent.Entities;
using Microsoft.EntityFrameworkCore;

namespace Sys.Entity.Models;

[Table("sys_api")]
public partial class SysApi:AuditableEntity<Guid>
{


    [Column("name")]
    [StringLength(64)]
    public string Name { get; set; }

    [Column("method")]
    [StringLength(10)]
    public string Method { get; set; }

    [Column("path")]
    [StringLength(255)]
    public string Path { get; set; }

    [Column("module")]
    [StringLength(64)]
    public string Module { get; set; }

    [Column("permission_code")]
    [StringLength(100)]
    public string PermissionCode { get; set; }


}