// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sys.Entity.Models;

/// <summary>
/// 页面权限
/// </summary>
[Table("sys_menu_permission")]
public partial class SysMenuPermission
{
    /// <summary>
    /// 主键
    /// </summary>
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// 父级
    /// </summary>
    [Column("parent_id")]
    public int? ParentId { get; set; }

    /// <summary>
    /// 菜单标题
    /// </summary>
    [Required]
    [Column("title")]
    [StringLength(64)]
    public string Title { get; set; }

    /// <summary>
    /// 菜单类型
    /// </summary>
    [Required]
    [Column("type", TypeName = "enum('catalog','menu','button')")]
    public string Type { get; set; }

    /// <summary>
    /// 前端路由
    /// </summary>
    [Column("route_path")]
    [StringLength(255)]
    public string RoutePath { get; set; }

    /// <summary>
    /// 组件路径
    /// </summary>
    [Column("component_path")]
    [StringLength(255)]
    public string ComponentPath { get; set; }

    /// <summary>
    /// 权限标识
    /// </summary>
    [Column("permission_code")]
    [StringLength(100)]
    public string PermissionCode { get; set; }

    /// <summary>
    /// 内嵌iframe地址
    /// </summary>
    [Column("iframe")]
    [StringLength(255)]
    public string Iframe { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    [Column("seq")]
    public int Seq { get; set; }

    /// <summary>
    /// 是否显示(1=显示,0=隐藏)
    /// </summary>
    [Column("visible")]
    public sbyte Visible { get; set; }

    /// <summary>
    /// 图标
    /// </summary>
    [Column("icon")]
    [StringLength(100)]
    public string Icon { get; set; }

    /// <summary>
    /// 外部链接
    /// </summary>
    [Column("external_url")]
    [StringLength(255)]
    public string ExternalUrl { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    [Column("created_time", TypeName = "datetime")]
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 创建人
    /// </summary>
    [Column("created_by")]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    /// <summary>
    /// 修改时间
    /// </summary>
    [Column("modified_time", TypeName = "datetime")]
    public DateTime? ModifiedTime { get; set; }

    /// <summary>
    /// 修改人
    /// </summary>
    [Column("modified_by")]
    [StringLength(50)]
    public string ModifiedBy { get; set; }
}