// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sys.Entity.Models;

/// <summary>
/// 角色与权限关联表
/// </summary>
public partial class SysRolePermission
{
    public string Id { get; set; }

    /// <summary>
    /// 角色ID
    /// </summary>
    public string RoleId { get; set; }

    /// <summary>
    /// 权限类型(menu=页面权限, api=接口权限)
    /// </summary>
    public string PermissionType { get; set; }

    /// <summary>
    /// 权限ID（对应sys_menu_permission.id 或 sys_api.id）
    /// </summary>
    public string PermissionId { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTime CreatedTime { get; set; }

    public virtual SysRole Role { get; set; }
}