// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Core.Entity.Entities;
using Core.Persistent.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Sys.Entity.Models;

/// <summary>
/// 角色
/// </summary>
[Table("sys_role")]
[Index("Code", Name = "sys_role_pk", IsUnique = true)]
[Index("Id", Name = "sys_role_pk_2", IsUnique = true)]
public partial class SysRole:BaseEntity<Guid>
{
    /// <summary>
    /// 主键
    /// </summary>
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// 角色代码
    /// </summary>
    [Required]
    [Column("code")]
    [StringLength(50)]
    public string Code { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// 启用状态
    /// </summary>
    [Column("enable")]
    public sbyte Enable { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<SysRolePermission> SysRolePermissions { get; set; } = new List<SysRolePermission>();

    [ForeignKey("RoleId")]
    [InverseProperty("Roles")]
    public virtual ICollection<SysUser> Users { get; set; } = new List<SysUser>();
}