// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sys.Entity.Models;

/// <summary>
/// 用户与角色关联表
/// </summary>
public partial class SysUserRole
{
    /// <summary>
    /// 用户ID
    /// </summary>
    public string UserId { get; set; }

    /// <summary>
    /// 角色ID
    /// </summary>
    public string RoleId { get; set; }

    public virtual SysRole Role { get; set; }

    public virtual SysUser User { get; set; }
}