// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Core.Persistent.Entities;

namespace Sys.Entity.Models;

/// <summary>
/// 系统用户表
/// </summary>
public partial class SysUser:AuditableEntity<Guid>
{


    /// <summary>
    /// 姓名
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// 用户名
    /// </summary>
    public string Username { get; set; } = null!;

    /// <summary>
    /// 密码
    /// </summary>
    public string Password { get; set; } = null!;

    /// <summary>
    /// 加密盐
    /// </summary>
    public string? Salt { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// 区号
    /// </summary>
    public int? MobileArea { get; set; }

    /// <summary>
    /// 手机号
    /// </summary>
    public string? MobilePhoneNumber { get; set; }

    /// <summary>
    /// 状态
    /// </summary>
    public int? Status { get; set; }

    /// <summary>
    /// 最后登录ip
    /// </summary>
    public string? LastLoginIp { get; set; }

    /// <summary>
    /// 最后登录时间
    /// </summary>
    public DateTime LastLoginTime { get; set; }

   
    public virtual ICollection<SysUserRole> SysUserRoles { get; set; } = new List<SysUserRole>();
}