// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Core.Persistent.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Sys.Entity.Models;

/// <summary>
/// 系统用户表
/// </summary>
[Table("sys_user")]
[Index("Id", Name = "sys_user_pk", IsUnique = true)]
[Index("Username", Name = "sys_user_pk_2", IsUnique = true)]
public partial class SysUser : AuditableEntity<Guid>
{
    /// <summary>
    /// 主键
    /// </summary>
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// 用户名
    /// </summary>
    [Required]
    [Column("username")]
    [StringLength(50)]
    public string Username { get; set; }

    /// <summary>
    /// 密码
    /// </summary>
    [Required]
    [Column("password")]
    [StringLength(100)]
    public string Password { get; set; }

    /// <summary>
    /// 加密盐
    /// </summary>
    [Column("salt")]
    [StringLength(50)]
    public string Salt { get; set; }

    /// <summary>
    /// 邮箱
    /// </summary>
    [Column("email")]
    [StringLength(50)]
    public string Email { get; set; }

    /// <summary>
    /// 区号
    /// </summary>
    [Column("mobile_area")]
    public int? MobileArea { get; set; }

    /// <summary>
    /// 手机号
    /// </summary>
    [Column("mobile_phone_number")]
    [StringLength(50)]
    public string MobilePhoneNumber { get; set; }

    /// <summary>
    /// 状态
    /// </summary>
    [Column("status")]
    public int? Status { get; set; }

    /// <summary>
    /// 最后登录ip
    /// </summary>
    [Column("last_login_ip")]
    [StringLength(40)]
    public string LastLoginIp { get; set; }

    /// <summary>
    /// 最后登录时间
    /// </summary>
    [Column("last_login_time", TypeName = "datetime")]
    public DateTime LastLoginTime { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    [Column("created_time", TypeName = "datetime")]
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 创建人
    /// </summary>
    [Column("created_by")]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    /// <summary>
    /// 修改时间
    /// </summary>
    [Column("modified_time", TypeName = "datetime")]
    public DateTime? ModifiedTime { get; set; }

    /// <summary>
    /// 修改人
    /// </summary>
    [Column("modified_by")]
    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Users")]
    public virtual ICollection<SysRole> Roles { get; set; } = new List<SysRole>();
}