// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Sys.Entity.Models;

/// <summary>
/// 用户与角色关联表
/// </summary>
public partial class SysUserRole
{
    /// <summary>
    /// 用户ID
    /// </summary>
    public Guid? UserId { get; set; } = null!;

    /// <summary>
    /// 角色ID
    /// </summary>
    public Guid? RoleId { get; set; } = null!;

    public virtual SysRole Role { get; set; } = null!;

    public virtual SysUser User { get; set; } = null!;
}