// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Core.Entity.Entities;

namespace Sys.Entity.Models;

/// <summary>
/// jwt黑名单
/// </summary>
public partial class SysJwtBlack:BaseEntity<Guid>
{


    /// <summary>
    /// token
    /// </summary>
    public string? Jti { get; set; }

    /// <summary>
    /// 过期时间
    /// </summary>
    public DateTime? ExpireAt { get; set; }

    public DateTime? CreatedAt { get; set; }
}