// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Core.Entity.Entities;

namespace Sys.Entity.Models;

/// <summary>
/// 登录日志
/// </summary>
public partial class SysLoginLog:BaseEntity<Guid>
{
   

    /// <summary>
    /// 用户名
    /// </summary>
    public string? Username { get; set; }

    /// <summary>
    /// IP地址
    /// </summary>
    public string? Ip { get; set; }

    /// <summary>
    /// 请求头
    /// </summary>
    public string? RequestHeader { get; set; }

    /// <summary>
    /// 登录成功
    /// </summary>
    public sbyte? Status { get; set; }

    /// <summary>
    /// 登录设备
    /// </summary>
    public string? Device { get; set; }

    /// <summary>
    /// 登录时间
    /// </summary>
    public DateTime? LogDate { get; set; }
}