// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Core.Entity.Entities;

namespace Sys.Entity.Models;

/// <summary>
/// 页面权限
/// </summary>
public partial class SysMenuPermission:TreeEntity<Guid>
{

    /// <summary>
    /// 菜单标题
    /// </summary>
    public string Title { get; set; } = null!;

    /// <summary>
    /// 菜单类型
    /// </summary>
    public string Type { get; set; } = null!;

    /// <summary>
    /// 前端路由
    /// </summary>
    public string? RoutePath { get; set; }

    /// <summary>
    /// 组件路径
    /// </summary>
    public string? ComponentPath { get; set; }

    /// <summary>
    /// 权限标识
    /// </summary>
    public string? PermissionCode { get; set; }

    /// <summary>
    /// 内嵌iframe地址
    /// </summary>
    public string? Iframe { get; set; }



    /// <summary>
    /// 是否显示(1=显示,0=隐藏)
    /// </summary>
    public sbyte Visible { get; set; }

    /// <summary>
    /// 图标
    /// </summary>
    public string? Icon { get; set; }

    /// <summary>
    /// 外部链接
    /// </summary>
    public string? ExternalUrl { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTime CreatedTime { get; set; }

    /// <summary>
    /// 创建人
    /// </summary>
    public string? CreatedBy { get; set; }

    /// <summary>
    /// 修改时间
    /// </summary>
    public DateTime? ModifyTime { get; set; }

    /// <summary>
    /// 修改人
    /// </summary>
    public string? ModifyBy { get; set; }

    public virtual ICollection<SysMenuApi> MenuApis { get; set; } = new List<SysMenuApi>();

}