// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Core.Entity.Entities;

namespace Sys.Entity.Models;

/// <summary>
/// 角色与权限关联表
/// </summary>
public partial class SysRolePermission:BaseEntity<Guid>
{

    /// <summary>
    /// 角色ID
    /// </summary>
    public Guid? RoleId { get; set; } = null!;

    /// <summary>
    /// 权限类型(menu=页面权限, api=接口权限)
    /// </summary>
    public string PermissionType { get; set; } = null!;

    /// <summary>
    /// 权限ID（对应sys_menu_permission.id 或 sys_api.id）
    /// </summary>
    public string PermissionId { get; set; } = null!;

    /// <summary>
    /// 创建时间
    /// </summary>
    public DateTime CreatedTime { get; set; }

    public virtual SysRole Role { get; set; } = null!;
}