// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Core.Entity.Entities;

namespace Sys.Entity.Models;

/// <summary>
/// 角色
/// </summary>
public partial class SysRole:BaseEntity<Guid>
{

    /// <summary>
    /// 角色代码
    /// </summary>
    public string Code { get; set; } = null!;

    /// <summary>
    /// 描述
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// 启用状态
    /// </summary>
    public bool Enable { get; set; }

    public virtual ICollection<SysRolePermission> SysRolePermissions { get; set; } = new List<SysRolePermission>();

    public virtual ICollection<SysUserRole> SysUserRoles { get; set; } = new List<SysUserRole>();
}