// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TestProject1.Models;

public partial class net_core_proContext : DbContext
{
    public net_core_proContext(DbContextOptions<net_core_proContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SysMenuPermission> SysMenuPermissions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<SysMenuPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_menu_permission");

            entity.Property(e => e.Id)
                .HasMaxLength(64)
                .HasComment("Id")
                .HasColumnName("id");
            entity.Property(e => e.Breadcrumbs)
                .HasComment("面包屑导航")
                .HasColumnName("breadcrumbs");
            entity.Property(e => e.Caption)
                .HasMaxLength(200)
                .HasComment("说明")
                .HasColumnName("caption");
            entity.Property(e => e.Color)
                .HasMaxLength(50)
                .HasComment("颜色")
                .HasColumnName("color");
            entity.Property(e => e.Disabled)
                .HasComment("禁用")
                .HasColumnName("disabled");
            entity.Property(e => e.External)
                .HasComment("外部")
                .HasColumnName("external");
            entity.Property(e => e.Icon)
                .HasMaxLength(100)
                .HasComment("图标")
                .HasColumnName("icon");
            entity.Property(e => e.IsDropdown)
                .HasComment("下拉")
                .HasColumnName("is_dropdown");
            entity.Property(e => e.Level)
                .HasComment("等级")
                .HasColumnName("level");
            entity.Property(e => e.Link)
                .HasMaxLength(255)
                .HasComment("链接")
                .HasColumnName("link");
            entity.Property(e => e.Module)
                .HasMaxLength(50)
                .HasComment("模块")
                .HasColumnName("module");
            entity.Property(e => e.ParentId)
                .HasMaxLength(64)
                .HasComment("父级")
                .HasColumnName("parent_id");
            entity.Property(e => e.Path)
                .HasMaxLength(255)
                .HasComment("路径")
                .HasColumnName("path");
            entity.Property(e => e.PermissionCode)
                .HasMaxLength(100)
                .HasComment("权限代码")
                .HasColumnName("permission_code");
            entity.Property(e => e.Search)
                .HasMaxLength(255)
                .HasComment("搜索")
                .HasColumnName("search");
            entity.Property(e => e.Sort)
                .HasComment("排序")
                .HasColumnName("sort");
            entity.Property(e => e.Target)
                .HasComment("目标")
                .HasColumnName("target");
            entity.Property(e => e.Title)
                .HasMaxLength(50)
                .HasComment("标题")
                .HasColumnName("title");
            entity.Property(e => e.Type)
                .HasMaxLength(64)
                .HasComment("类型")
                .HasColumnName("type");
            entity.Property(e => e.Url)
                .HasMaxLength(255)
                .HasComment("链接")
                .HasColumnName("url");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}