// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sys.Entity.Models;

public partial class SysDbContext : DbContext
{
    public SysDbContext(DbContextOptions<SysDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SysApi> SysApis { get; set; }

    public virtual DbSet<SysJwtBlack> SysJwtBlacks { get; set; }

    public virtual DbSet<SysLoginLog> SysLoginLogs { get; set; }

    public virtual DbSet<SysMenuPermission> SysMenuPermissions { get; set; }

    public virtual DbSet<SysRole> SysRoles { get; set; }

    public virtual DbSet<SysRolePermission> SysRolePermissions { get; set; }

    public virtual DbSet<SysUser> SysUsers { get; set; }

    public virtual DbSet<SysUserRole> SysUserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<SysApi>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_api");

            entity.Property(e => e.Id)
                .HasMaxLength(64)
                .HasColumnName("id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasComment("创建人")
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedTime)
                .HasComment("创建时间")
                .HasColumnType("datetime")
                .HasColumnName("created_time");
            entity.Property(e => e.Method)
                .HasMaxLength(10)
                .HasColumnName("method");
            entity.Property(e => e.ModifyBy)
                .HasMaxLength(50)
                .HasComment("修改人")
                .HasColumnName("modify_by");
            entity.Property(e => e.ModifyTime)
                .HasComment("修改时间")
                .HasColumnType("datetime")
                .HasColumnName("modify_time");
            entity.Property(e => e.Module)
                .HasMaxLength(64)
                .HasColumnName("module");
            entity.Property(e => e.Name)
                .HasMaxLength(64)
                .HasColumnName("name");
            entity.Property(e => e.Path)
                .HasMaxLength(255)
                .HasColumnName("path");
            entity.Property(e => e.PermissionCode)
                .HasMaxLength(100)
                .HasColumnName("permission_code");
        });

        modelBuilder.Entity<SysJwtBlack>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_jwt_black", tb => tb.HasComment("jwt黑名单"));

            entity.HasIndex(e => e.Id, "sys_jwt_black_pk_2").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(64)
                .HasComment("ID")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.ExpireAt)
                .HasComment("过期时间")
                .HasColumnType("datetime")
                .HasColumnName("expire_at");
            entity.Property(e => e.Jti)
                .HasMaxLength(255)
                .HasComment("token")
                .HasColumnName("jti");
        });

        modelBuilder.Entity<SysLoginLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_login_log", tb => tb.HasComment("登录日志"));

            entity.Property(e => e.Id)
                .HasMaxLength(64)
                .HasComment("主键")
                .HasColumnName("id");
            entity.Property(e => e.Device)
                .HasMaxLength(255)
                .HasComment("登录设备")
                .HasColumnName("device");
            entity.Property(e => e.Ip)
                .HasMaxLength(64)
                .HasComment("IP地址")
                .HasColumnName("ip");
            entity.Property(e => e.LogDate)
                .HasComment("登录时间")
                .HasColumnType("datetime")
                .HasColumnName("log_date");
            entity.Property(e => e.RequestHeader)
                .HasComment("请求头")
                .HasColumnType("text")
                .HasColumnName("request_header");
            entity.Property(e => e.Status)
                .HasComment("登录成功")
                .HasColumnName("status");
            entity.Property(e => e.Username)
                .HasMaxLength(50)
                .HasComment("用户名")
                .HasColumnName("username");
        });

        modelBuilder.Entity<SysMenuPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_menu_permission", tb => tb.HasComment("页面权限"));

            entity.Property(e => e.Id)
                .HasMaxLength(64)
                .HasColumnName("id");
            entity.Property(e => e.ComponentPath)
                .HasMaxLength(255)
                .HasComment("组件路径")
                .HasColumnName("component_path");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasComment("创建人")
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedTime)
                .HasComment("创建时间")
                .HasColumnType("datetime")
                .HasColumnName("created_time");
            entity.Property(e => e.ExternalUrl)
                .HasMaxLength(255)
                .HasComment("外部链接")
                .HasColumnName("external_url");
            entity.Property(e => e.Icon)
                .HasMaxLength(100)
                .HasComment("图标")
                .HasColumnName("icon");
            entity.Property(e => e.Iframe)
                .HasMaxLength(255)
                .HasComment("内嵌iframe地址")
                .HasColumnName("iframe");
            entity.Property(e => e.ModifyBy)
                .HasMaxLength(50)
                .HasComment("修改人")
                .HasColumnName("modify_by");
            entity.Property(e => e.ModifyTime)
                .HasComment("修改时间")
                .HasColumnType("datetime")
                .HasColumnName("modify_time");
            entity.Property(e => e.ParentId)
                .HasComment("父级")
                .HasColumnName("parent_id");
            entity.Property(e => e.PermissionCode)
                .HasMaxLength(100)
                .HasComment("权限标识")
                .HasColumnName("permission_code");
            entity.Property(e => e.RoutePath)
                .HasMaxLength(255)
                .HasComment("前端路由")
                .HasColumnName("route_path");
            // entity.Property(e => e.Seq)
            //     .HasComment("排序")
            //     .HasColumnName("seq");
            entity.Property(e => e.Title)
                .HasMaxLength(64)
                .HasComment("菜单标题")
                .HasColumnName("title");
            entity.Property(e => e.Type)
                .HasMaxLength(25)
                .HasComment("菜单类型")
                // .HasColumnType("enum('group','catalog','menu','button')")
                .HasColumnName("type");
            entity.Property(e => e.Visible)
                .HasDefaultValueSql("'1'")
                .HasComment("是否显示(1=显示,0=隐藏)")
                .HasColumnName("visible");
        });

        modelBuilder.Entity<SysRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_role", tb => tb.HasComment("角色"));

            entity.HasIndex(e => e.Code, "sys_role_pk").IsUnique();

            entity.HasIndex(e => e.Id, "sys_role_pk_2").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(64)
                .HasColumnName("id");
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .HasComment("角色代码")
                .HasColumnName("code");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasComment("描述")
                .HasColumnName("description");
            entity.Property(e => e.Enable)
                .HasDefaultValueSql("'1'")
                .HasComment("启用状态")
                .HasColumnName("enable");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasComment("名称")
                .HasColumnName("name");
        });

        modelBuilder.Entity<SysRolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_role_permission", tb => tb.HasComment("角色与权限关联表"));

            entity.HasIndex(e => e.RoleId, "fk_rolepermission_role");

            entity.Property(e => e.Id)
                .HasMaxLength(64)
                .HasColumnName("id");
            entity.Property(e => e.CreatedTime)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建时间")
                .HasColumnType("datetime")
                .HasColumnName("created_time");
            entity.Property(e => e.PermissionId)
                .HasMaxLength(64)
                .HasComment("权限ID（对应sys_menu_permission.id 或 sys_api.id）")
                .HasColumnName("permission_id");
            entity.Property(e => e.PermissionType)
                .HasComment("权限类型(menu=页面权限, api=接口权限)")
                .HasColumnType("enum('menu','api')")
                .HasColumnName("permission_type");
            entity.Property(e => e.RoleId)
                .HasMaxLength(64)
                .HasComment("角色ID")
                .HasColumnName("role_id");

            entity.HasOne(d => d.Role).WithMany(p => p.SysRolePermissions)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("fk_rolepermission_role");
        });

        modelBuilder.Entity<SysUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("sys_user", tb => tb.HasComment("系统用户表"));

            entity.HasIndex(e => e.Id, "sys_user_pk").IsUnique();

            entity.HasIndex(e => e.Username, "sys_user_pk_2").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(64)
                .HasColumnName("id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasComment("创建人")
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedTime)
                .HasComment("创建时间")
                .HasColumnType("datetime")
                .HasColumnName("created_time");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .HasComment("邮箱")
                .HasColumnName("email");
            entity.Property(e => e.LastLoginIp)
                .HasMaxLength(40)
                .HasComment("最后登录ip")
                .HasColumnName("last_login_ip");
            entity.Property(e => e.LastLoginTime)
                .HasComment("最后登录时间")
                .HasColumnType("datetime")
                .HasColumnName("last_login_time");
            entity.Property(e => e.MobileArea)
                .HasComment("区号")
                .HasColumnName("mobile_area");
            entity.Property(e => e.MobilePhoneNumber)
                .HasMaxLength(50)
                .HasComment("手机号")
                .HasColumnName("mobile_phone_number");
            entity.Property(e => e.ModifyBy)
                .HasMaxLength(50)
                .HasComment("修改人")
                .HasColumnName("modify_by");
            entity.Property(e => e.ModifyTime)
                .HasComment("修改时间")
                .HasColumnType("datetime")
                .HasColumnName("modify_time");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasComment("姓名")
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .HasComment("密码")
                .HasColumnName("password");
            entity.Property(e => e.Salt)
                .HasMaxLength(50)
                .HasComment("加密盐")
                .HasColumnName("salt");
            entity.Property(e => e.Status)
                .HasComment("状态")
                .HasColumnName("status");
            entity.Property(e => e.Username)
                .HasMaxLength(50)
                .HasComment("用户名")
                .HasColumnName("username");
        });

        modelBuilder.Entity<SysUserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.ToTable("sys_user_role", tb => tb.HasComment("用户与角色关联表"));

            entity.HasIndex(e => e.RoleId, "fk_userrole_role");

            entity.Property(e => e.UserId)
                .HasMaxLength(64)
                .HasComment("用户ID")
                .HasColumnName("user_id");
            entity.Property(e => e.RoleId)
                .HasMaxLength(64)
                .HasComment("角色ID")
                .HasColumnName("role_id");

            entity.HasOne(d => d.Role).WithMany(p => p.SysUserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("fk_userrole_role");

            entity.HasOne(d => d.User).WithMany(p => p.SysUserRoles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_userrole_user");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}